### ISSUE TITLE
Dockerfile for sergiomtzlosa/ubuntu-nmag

### ISSUE THREAD

**Issue by mhanberry1** [sergiomtzlosa/docker-nmag#1]
Could you add the original dockerfile used to create the sergiomtzlosa/ubuntu-nmag image?

Building NMAG in a docker container has been a major challenge, so it would be useful to see how you acheived this.

**Comment by sergiomtzlosa** [comment]
Hi,

I took the original vmware image and transform it into a docker image. I used this guide to achive the conversion:

https://blog.inslash.com/how-to-convert-vmdk-to-a-docker-image-be939745ed8a

Before this, I tried several times to build a docker image from scratch and it was very hard due to nmag never compiles onto the old ubuntu image, then I decided to think a different solution.

Sorry, there is no Dockerfile to build the image, just the image itself.

Here is the base docker image with a Dockerfile to build it: 

https://mega.nz/#!3NwByYpY!yu11bXcBhdxs0Z0fy8xwFcGJv6V2DwjKFmwUorFBA1k

Regards
